### ISSUE TITLE
Fix for compilation error on 2.6.34

### ISSUE THREAD

**Issue by tadzik** [tetromino/lenovo-sl-laptop#5]
Hello,
Here's my quick and dirty fix for compilation issue on 2.6.34. backlight_device_register() needs some optional argument, luckily passing NULL works fine (at least for me). Patch [here](http://wklej.org/id/335841/)

EDIT: New patch [here](http://wklej.org/id/335869/), done more-less the right way (almost copied from some grepped out code from the linux kernel)

EDIT2: Since author does not seem to give attention to the case and I've alredy seen people who need this, I created a fork (http://github.com/tadzik/lenovo-sl-laptop). I'm not really into kernel module development, but I'll try to take care of it.

**Comment by xuzhen** [comment]
here is a better patch:  http://wklej.org/id/375151/
works with kernel<2.6.34 and >=2.6.34

**Comment by tadzik** [comment]
FYI, applied in my fork.
